FROM node:22-alpine AS deps
WORKDIR /app
RUN apk add --no-cache python3 make g++
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG VITE_THEGRAPH_API_KEY
ARG VITE_ALCHEMY_API_KEY
ARG VITE_UNISWAP_PROXY_URL
ARG VITE_OLLAMA_PROXY_URL=/hooklens-ollama
ARG VITE_HOOKLENS_DEBUG_SUBGRAPH=false
ARG VITE_HOOKLENS_DEBUG_QUOTES=false
ENV VITE_THEGRAPH_API_KEY=$VITE_THEGRAPH_API_KEY
ENV VITE_ALCHEMY_API_KEY=$VITE_ALCHEMY_API_KEY
ENV VITE_UNISWAP_PROXY_URL=$VITE_UNISWAP_PROXY_URL
ENV VITE_OLLAMA_PROXY_URL=$VITE_OLLAMA_PROXY_URL
ENV VITE_HOOKLENS_DEBUG_SUBGRAPH=$VITE_HOOKLENS_DEBUG_SUBGRAPH
ENV VITE_HOOKLENS_DEBUG_QUOTES=$VITE_HOOKLENS_DEBUG_QUOTES
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080
COPY package*.json ./
COPY server.js ./
COPY --from=build /app/dist ./dist
EXPOSE 8080
CMD ["npm", "run", "start"]
